name: Azure Static Web Apps Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    # Deploy to Azure Static Web Apps
    # Note: The syntax ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} is correct for GitHub Actions
    # Your IDE might show warnings, but this is the proper way to access secrets in GitHub Actions
    - name: Deploy to Azure Static Web Apps
      id: deploy-to-azure-swa
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "/" # Root of the project
        api_location: "" # Leave empty if no API
        output_location: "dist" # The build output folder
        skip_app_build: false # Set to true if you want to use the build step above
